apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: database
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:13-alpine
            env:
            - name: PGHOST
              value: postgres-coordinator
            - name: PGUSER
              value: vault5_user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PGDATABASE
              value: vault5
            command:
            - sh
            - -c
            - |
              pg_dump --format=custom --compress=9 --file=/backup/vault5-$(date +%Y%m%d-%H%M%S).dump
              # Optionally upload to S3 or other storage
              # aws s3 cp /backup/*.dump s3://vault5-backups/
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi