global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@vault5.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'admin@vault5.com'